FROM python:3.11.2-alpine3.16

WORKDIR /app

COPY requirements.txt ./
COPY requirements-test.txt ./

RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

COPY . .

CMD ["pytest", "-v"]